### ISSUE TITLE
Auto-hypenator

### ISSUE THREAD

**Issue by amenk** [straschek-io/typo3-hyphenator#3]
Did you know / consider the use of https://packagist.org/packages/org_heigl/hyphenator ? This would work without a dictionary.

Would you eventually accept a pull request to include this?

**Comment by amenk** [comment]
We will probably go with a JS polyfill though .. https://github.com/mnater/Hyphenopoly

**Comment by mockmeup** [comment]
@amenk Just my 2 cents: If I understand correctly what org_heigl/hyphenator is doing, then this is in contradiction with the intention of this extension.

Which is – as I understand and use it – in fact NOT to have automatic hyphenation, because automatic hyphenation often lead to "ugly" results:

> ... ... .. ..... ... Ar-
> beiterunfallversicherungsgesetz

> ... ... .. ..... Arbeiterun-
> fallversicherungsgesetz

Working with a dictionary instead gives you control over the output:

> Arbeiter-
> unfall-
> versicherungs-
> gesetz

**Comment by straschek-io** [comment]
@mockmeup is absolutely right in his opinion. I am closing the topic due to irrelevance, as a completely different approach is being taken here.

**Comment by amenk** [comment]
Okay :-)
